import assert from "node:assert/strict"
import { createHash } from "node:crypto"
import { DatabaseSync } from "node:sqlite"
import test from "node:test"
import { D1OperationRepository } from "../packages/runtime-cloudflare/src/d1-operation-repository.js"
import { PROVISIONING_CREATE_REQUEST_SCHEMA, resumeProvisioningAllocation, routeProvisioningApi } from "../packages/runtime-cloudflare/src/provisioning-api.js"
import { STATIC_ARTIFACT_IMPORT_REQUEST_SCHEMA } from "../packages/runtime-cloudflare/src/static-artifact-import.js"

const hash = (value: string | Uint8Array) => createHash("sha256").update(value).digest("hex")
const artifactText = JSON.stringify({ schema: "blocks-engine/php-transformer/site-artifact/v1", root: "website", entrypoint: "website/index.html", files: [{ path: "website/index.html", content: "ok" }] })
const artifact = new TextEncoder().encode(artifactText); const digest = hash(artifact)
type Db = D1Database & { sqlite: DatabaseSync }
function database(): Db {
  const sqlite = new DatabaseSync(":memory:")
  return Object.assign({ prepare(query: string) { const statement = sqlite.prepare(query); let values: unknown[] = []; return { bind(...next: unknown[]) { values = next; return this }, async run() { return { meta: { changes: statement.run(...values).changes } } }, async first<T>() { return statement.get(...values) as T | null }, async all<T>() { return { results: statement.all(...values) as T[] } } } }, async batch(statements: Array<{ run: () => Promise<{ meta: { changes: number } }> }>) { sqlite.exec("BEGIN"); try { const results = []; for (const statement of statements) results.push(await statement.run()); sqlite.exec("COMMIT"); return results } catch (error) { sqlite.exec("ROLLBACK"); throw error } } } as unknown as D1Database, { sqlite })
}
class Bucket {
  objects = new Map<string, Uint8Array>(); gets = 0; puts = 0; race?: Uint8Array; dropSuccessfulPut = false
  async get(key: string) { this.gets++; const value = this.objects.get(key); return value ? { size: value.byteLength, etag: hash(value), arrayBuffer: async () => value.slice().buffer } : null }
  async put(key: string, value: string | Uint8Array, options?: { onlyIf?: { etagDoesNotMatch?: string } }) { this.puts++; const bytes = typeof value === "string" ? new TextEncoder().encode(value) : value; if (options?.onlyIf?.etagDoesNotMatch === "*" && this.objects.has(key)) return null; if (this.race && options?.onlyIf) { this.objects.set(key, this.race); this.race = undefined; return null } if (!this.dropSuccessfulPut) this.objects.set(key, bytes.slice()); return { key } }
}
function runtime(db = database(), bucket = new Bucket(), tokens?: unknown, maxSites = 2) {
  bucket.objects.set(`sites/provisioning/import-artifacts/${digest}.json`, artifact)
  const records = tokens ?? [{ id: "a", principal: "a", digest: hash("good"), scopes: ["sites:create", "sites:read", "sites:import", "operations:read"], expiresAt: "2099-01-01T00:00:00.000Z", maxSites }]
  return { env: { WORDPRESS_STATE_DATABASE: db, WORDPRESS_STATE_BUCKET: bucket as unknown as R2Bucket, WORDPRESS_SITE_CONTEXTS: JSON.stringify([{ id: "alpha", hostname: "alpha.example", origin: "https://alpha.example" }, { id: "beta", hostname: "beta.example", origin: "https://beta.example" }]), WORDPRESS_API_TOKENS: JSON.stringify(records) }, db, bucket, operations: new D1OperationRepository(db) }
}
function createRequest(key = "create-1", change: Partial<{ sha256: string; size: number; r2Key: string; title: string }> = {}, token = "good") {
  const sha256 = change.sha256 ?? digest; const size = change.size ?? artifact.byteLength
  return new Request("https://control.invalid/v1/sites", { method: "POST", headers: { authorization: `Bearer ${token}`, "idempotency-key": key }, body: JSON.stringify({ schema: PROVISIONING_CREATE_REQUEST_SCHEMA, idempotencyKey: key, artifact: { sha256, size, r2Key: change.r2Key ?? `sites/provisioning/import-artifacts/${sha256}.json` }, import: { slug: "site", name: "Site", siteTitle: change.title ?? "Site" } }) })
}
async function create(runtime: ReturnType<typeof runtime>, key = "create-1") { return routeProvisioningApi(createRequest(key), runtime.env, runtime.operations) }
function count(db: Db, table: string) { const exists = db.sqlite.prepare("SELECT name FROM sqlite_master WHERE type = 'table' AND name = ?").get(table); return exists ? Number((db.sqlite.prepare(`SELECT COUNT(*) AS count FROM ${table}`).get() as { count: number }).count) : 0 }

test("auth failures, malformed config, expiry, and scope stop before body and R2 reads", async () => {
  for (const config of [undefined, [], [{ id: "a", principal: "a", digest: hash("good"), scopes: ["sites:create"], expiresAt: "2000-01-01T00:00:00.000Z", maxSites: 1 }], [{ id: "a", principal: "a", digest: hash("good"), scopes: ["sites:read"], expiresAt: "2099-01-01T00:00:00.000Z", maxSites: 1 }]]) {
    const r = runtime(database(), new Bucket(), config); const response = await routeProvisioningApi(createRequest("key", {}, config === undefined ? "bad" : "good"), r.env, r.operations); assert.ok([401, 403].includes(response.status)); assert.equal(r.bucket.gets, 0)
  }
})
test("invalid, missing, and oversized artifacts create zero allocations", async () => {
  for (const change of [{ sha256: "bad" }, { sha256: "f".repeat(64) }, { size: 5 * 1024 * 1024 }]) { const r = runtime(); assert.ok((await routeProvisioningApi(createRequest("key", change), r.env, r.operations)).status >= 400); assert.equal(count(r.db, "wp_codebox_api_sites"), 0) }
})
test("registered active contexts are excluded", async () => { const r = runtime(); await r.operations.createOrConverge({ id: "alpha", hostname: "alpha.example", origin: "https://alpha.example" }, { idempotencyKey: "legacy", fingerprint: "x", artifact: { r2Key: "x", sha256: digest, size: artifact.byteLength }, options: { slug: "x", name: "x", siteTitle: "x" } }); const body = await (await create(r)).json() as { site: { id: string } }; assert.equal(body.site.id, "beta") })
test("exact and concurrent same-key creates converge", async () => { const r = runtime(); const [one, two] = await Promise.all([create(r), create(r)]); assert.equal(one.status, 202); assert.deepEqual(await one.json(), await two.json()); assert.equal(count(r.db, "wp_codebox_api_sites"), 1) })
test("changed fingerprints conflict without another allocation", async () => { const r = runtime(); await create(r); const response = await routeProvisioningApi(createRequest("create-1", { title: "Changed" }), r.env, r.operations); assert.equal(response.status, 409); assert.equal(count(r.db, "wp_codebox_api_sites"), 1) })
test("create replay honors current site restrictions", async () => { const r = runtime(); await create(r); const records = JSON.parse(r.env.WORDPRESS_API_TOKENS) as Array<Record<string, unknown>>; records[0].sites = ["beta"]; r.env.WORDPRESS_API_TOKENS = JSON.stringify(records); assert.equal((await create(r)).status, 404); assert.equal(count(r.db, "wp_codebox_api_sites"), 1) })
test("concurrent distinct keys allocate unique contexts", async () => { const r = runtime(); await Promise.all([create(r, "one"), create(r, "two")]); const ids = r.db.sqlite.prepare("SELECT site_id FROM wp_codebox_api_sites ORDER BY site_id").all() as Array<{ site_id: string }>; assert.deepEqual(ids.map((row) => row.site_id), ["alpha", "beta"]) })
test("maxSites concurrency distinguishes quota from pool exhaustion", async () => { const quota = runtime(database(), new Bucket(), undefined, 1); const responses = await Promise.all([create(quota, "one"), create(quota, "two")]); assert.equal(responses.filter((response) => response.status === 202).length, 1); const rejected = responses.find((response) => response.status !== 202)!; assert.equal((await rejected.json() as { error: { code: string } }).error.code, "quota_exceeded"); assert.equal(count(quota.db, "wp_codebox_api_sites"), 1); const pool = runtime(database(), new Bucket(), undefined, 3); await Promise.all([create(pool, "one"), create(pool, "two")]); const pr = await create(pool, "three"); assert.equal((await pr.json() as { error: { code: string } }).error.code, "capacity_exhausted") })
test("conditional R2 winner is re-read and verified, while missing or conflicting winners block operation", async () => { const r = runtime(); r.bucket.race = artifact; const ok = await create(r); assert.equal(ok.status, 202); const bad = runtime(); bad.bucket.race = new TextEncoder().encode("bad"); assert.equal((await create(bad)).status, 409); assert.equal(count(bad.db, "wp_codebox_operations"), 0); const missing = runtime(); missing.bucket.dropSuccessfulPut = true; assert.equal((await create(missing)).status, 409); assert.equal(count(missing.db, "wp_codebox_operations"), 0) })
test("scheduler recovery helper converges allocation without operation, API link, and destination copy", async () => { const r = runtime(); r.db.sqlite.exec("CREATE TABLE wp_codebox_api_sites (site_id TEXT PRIMARY KEY, principal TEXT NOT NULL, idempotency_key TEXT NOT NULL, fingerprint TEXT NOT NULL, artifact_sha256 TEXT NOT NULL, artifact_size INTEGER NOT NULL, slug TEXT NOT NULL, name TEXT NOT NULL, site_title TEXT NOT NULL, operation_id TEXT, created_at INTEGER NOT NULL, UNIQUE(principal, idempotency_key)); CREATE TABLE wp_codebox_api_operation_links (principal TEXT NOT NULL, site_id TEXT NOT NULL, operation_id TEXT NOT NULL, kind TEXT NOT NULL, idempotency_key TEXT NOT NULL, PRIMARY KEY (principal,site_id,operation_id), UNIQUE(principal,site_id,kind,idempotency_key));"); r.db.sqlite.prepare("INSERT INTO wp_codebox_api_sites VALUES ('alpha','a','one','fingerprint',?,?, 'site','Site','Site',NULL,1)").run(digest, artifact.byteLength); const site = { id: "alpha", hostname: "alpha.example", origin: "https://alpha.example" }; const operation = await resumeProvisioningAllocation(r.env, site, r.operations); assert.ok(operation); r.db.sqlite.prepare("DELETE FROM wp_codebox_api_operation_links").run(); r.db.sqlite.prepare("UPDATE wp_codebox_api_sites SET operation_id = ? WHERE site_id = 'alpha'").run(operation!.operationId); await resumeProvisioningAllocation(r.env, site, r.operations); assert.equal(count(r.db, "wp_codebox_api_operation_links"), 1); assert.ok(r.bucket.objects.has(`sites/alpha/import-artifacts/${digest}.json`)) })
test("cross-principal and site-restricted reads and imports fail closed", async () => { const tokens = [{ id: "a", principal: "a", digest: hash("good"), scopes: ["sites:create", "sites:read", "sites:import", "operations:read"], expiresAt: "2099-01-01T00:00:00.000Z", maxSites: 2 }, { id: "b", principal: "b", digest: hash("other"), scopes: ["sites:read", "sites:import"], expiresAt: "2099-01-01T00:00:00.000Z", maxSites: 2, sites: ["beta"] }]; const r = runtime(database(), new Bucket(), tokens); await create(r); for (const url of ["/v1/sites/alpha", "/v1/sites/alpha/imports"]) { const response = await routeProvisioningApi(new Request(`https://control.invalid${url}`, { method: url.endsWith("imports") ? "POST" : "GET", headers: { authorization: "Bearer other", "idempotency-key": "x" }, body: url.endsWith("imports") ? "{}" : undefined }), r.env, r.operations); assert.equal(response.status, 404) } })
test("not-ready import is rejected and ready exact replay converges with an API link", async () => { const r = runtime(); const body = await (await create(r)).json() as { site: { id: string; operation: string } }; const url = `https://control.invalid/v1/sites/${body.site.id}/imports`; const importBody = { schema: STATIC_ARTIFACT_IMPORT_REQUEST_SCHEMA, idempotencyKey: "import-1", artifact: { r2Key: `sites/${body.site.id}/import-artifacts/${digest}.json`, sha256: digest, size: artifact.byteLength }, import: { slug: "import", name: "Import", siteTitle: "Import" } }; const pending = await routeProvisioningApi(new Request(url, { method: "POST", headers: { authorization: "Bearer good", "idempotency-key": "import-1" }, body: JSON.stringify(importBody) }), r.env, r.operations); assert.equal(pending.status, 409); r.db.sqlite.prepare("UPDATE wp_codebox_operations SET state = 'succeeded' WHERE site_id = ?").run(body.site.id); const one = await routeProvisioningApi(new Request(url, { method: "POST", headers: { authorization: "Bearer good", "idempotency-key": "import-1" }, body: JSON.stringify(importBody) }), r.env, r.operations); const two = await routeProvisioningApi(new Request(url, { method: "POST", headers: { authorization: "Bearer good", "idempotency-key": "import-1" }, body: JSON.stringify(importBody) }), r.env, r.operations); assert.deepEqual(await one.json(), await two.json()); assert.equal(count(r.db, "wp_codebox_api_operation_links"), 2) })
test("unlinked same-site legacy operations return 404", async () => { const r = runtime(); const body = await (await create(r)).json() as { site: { id: string } }; r.db.sqlite.prepare("UPDATE wp_codebox_operations SET state = 'succeeded' WHERE site_id = ?").run(body.site.id); const legacy = await r.operations.createOrConverge({ id: body.site.id, hostname: `${body.site.id}.example`, origin: `https://${body.site.id}.example` }, { idempotencyKey: "legacy", fingerprint: "legacy", artifact: { r2Key: "legacy", sha256: digest, size: artifact.byteLength }, options: { slug: "legacy", name: "Legacy", siteTitle: "Legacy" } }); const response = await routeProvisioningApi(new Request(`https://control.invalid/v1/sites/${body.site.id}/operations/${legacy.operation.operationId}`, { headers: { authorization: "Bearer good" } }), r.env, r.operations); assert.equal(response.status, 404) })
test("operation resources expose retry, error, and receipt without ownership tokens", async () => { const r = runtime(); const body = await (await create(r)).json() as { site: { id: string; operation: string } }; const id = body.site.operation.split("/").at(-1)!; r.db.sqlite.prepare("UPDATE wp_codebox_operations SET state='retryable', retry_at=1, error_code='x', error_message='y' WHERE site_id=? AND operation_id=?").run(body.site.id, id); const value = await (await routeProvisioningApi(new Request(`https://control.invalid/v1/sites/${body.site.id}/operations/${id}`, { headers: { authorization: "Bearer good" } }), r.env, r.operations)).text(); assert.match(value, /retryAt/); assert.match(value, /"error"/); assert.doesNotMatch(value, /claimToken|principal/) })
test("route, method, Allow, and /v1 precedence behavior is explicit", async () => { const r = runtime(); assert.equal((await routeProvisioningApi(new Request("https://x.invalid/v1/wordpress"), r.env, r.operations)).status, 404); const response = await routeProvisioningApi(new Request("https://x.invalid/v1/sites", { method: "GET" }), r.env, r.operations); assert.equal(response.status, 405); assert.equal(response.headers.get("allow"), "POST"); assert.equal((await routeProvisioningApi(new Request("https://x.invalid/not-v1"), r.env, r.operations)).status, 404) })
